### ISSUE TITLE
Refactor the library to actually not need global variables and work properly with CommonJS/AMD/ES6 module systems.

### ISSUE THREAD

**Issue by lesion** [remotestorage/remotestorage.js#949] opened 2016-09-22 23:05 UTC
Like @skddc wrote in d4dd748, I agree that a refactoring is needed to simplify the usage of remoteStorage.
### Now:
1. Download remotestorage.js
2. Download a data module
3. Choose a build (AMD / nocache / min ...)
4. Include in your html

``` html
<script src='remotestorage.js'></script>
<script src='remotestorage-bookmarks.js'></script>
```
### Now with webpack / browserify / bower / npm

This is currently not working or at least I'm not able to make it works!
1. `npm install remotestoragejs --save-dev`
2. `npm install remotestorage/modules --save-dev` // fetch from github not from npm registry

``` js
require('remotestoragejs/release/stable/remotestorage.amd.js');
// window.RemoteStorage is now available
require('remotestoragejs-modules/bookmarks');
// dependencies issues & RemoteStorage in global scope !
```
### What do I expect
1. `npm install remotestoragejs --save-dev`
2. `npm install remotestoragejs-modules --save-dev`

``` js
var RemoteStorage = require('remotestoragejs')
var Bookmarks = require('remotestoragejs-modules/bookmarks')

// ES6 
// import RemoteStorage from 'remotestoragejs'
// import { bookmarks } from 'remotestoragejs-modules'
```

I think this will result in a cleaner code, without polluting the global namespace,
with declared dependencies between different part of the library.
let me know what do you think, to me porting the lib to 2016 and makes it
usable with modern tools will attract more people to working with it.
I think this is not a lot of work and if you agree with me I'm starting to do it.

**Comment by skddc** [comment] 2016-09-23 11:33
By the way, I think we should also remove the no-cache build with this move. At the moment, disabling caching in the normal build will still cache with the SEEN strategy I think, so that might require an API change or addition (or we can load based on name or sth).

**Comment by lesion** [comment] 2016-09-23 23:57
Nice for me to have a npm package for each single modules.

I've started to work on removing global RemoteStorage var and package the lib
with webpack in UMD (so everything could import it) on [feature/949-noglobal](https://github.com/remotestorage/remotestorage.js/compare/feature/949-noglobal) branch.

It's pretty much working right now with my setup but only in browser,
not in node because there's the XMLHttpRequest dependency from webfinder.js !
To fix this I think we can tell webpack to export a separate node package (dirty) or to 
convince @silverbucket to stop requiring `xmlhttprequest` and use an isomorphic
module (like [this one](https://www.npmjs.com/package/isomorphic-fetch)).

Something is missing of course, (e.g. [this](https://github.com/remotestorage/remotestorage.js/blob/master/src/sync.js#L881) is not working right now)

Feedback welcome :)

**Comment by lesion** [comment] 2016-09-26 00:17
I've done some steps:

1. [feature/949-noglobal](https://github.com/remotestorage/remotestorage.js/compare/feature/949-noglobal) branch is where the I'm working on (I'm pretty happy with this, the only thing I cannot manage to make works are tests, because `jaribu` (the test thing you are using) doesn't have a way to specify a different baseUrl to requirejs, so it searches from ./ and not from ./src.

2. an example on how separated data modules could be [here](https://github.com/lesion/remotestorage-module-bookmarks) (this is a copy/paste from your bookmarks module implementation with some little changes, so instead relying on a global RemoteStorage, it requires it locally).

3. a test [repo](https://github.com/lesion/rs-test) to try this new configuration in different environment.
all implementations there, are working as expected using the same exported library (getting npm package from the [branch](https://github.com/lesion/rs-test/blob/master/webpack-browser-es5/package.json#L8) and using the test bookmarks module in the other repo)

**Comment by skddc** [comment] 2016-09-27 11:53
This is all great!

Regarding webfinger.js and jaribu, I'm actually staying with @silverbucket in Prague from this Thursday to Tuesday next week. So we can have a look at it together and also fix anything else that we might need in those for release.

**Comment by skddc** [comment] 2016-09-27 12:20
A few other things we need to solve:

### Module docs and schemas

At the moment they are available combined for all modules, including all known schemas/types under the [module repo's GitHub pages URL](https://remotestorage.github.io/modules). However, we already had discussions going on about switching to a more suitable documentation framework and also about separating schema definitions from module source code. Both things are connected by the schemas ideally being documented and searchable, but also *shareable* between modules. And the definitions should also be available under their JSON-LD type/context URLs.

Now, these are a lot of issues and not necessarily possible or reasonable to solve short-term imo. The main question is really, if we currently want to generate NaturalDocs pages for every single module repo , and if yes, then how to index and link them. I think ND is even less suitable when not using its menu and search functionality, so this might be a good time to switch the module docs to something both simpler and better suitable for JavaScript/ES6, as well as creating a module index, perhaps on the wiki. Even a plain README.md might work for most modules, as the APIs usually aren't complex.

Would love to hear what others think about this.

### Module console

We currently ship a working interactive node repl in the modules repo, which makes it easy to live-code modules and/or play around with them. Should probably move to its own npm module, included as a dev dependency in the module repos/packages.

### No-cache build

Currently, only the no-cache build will actually never cache anything, even when calling `caching.disable()` in the normal one. This is done by the caching source not being included in the build, and RS initializing then recognizing that caching is not a supported feature. Personally, I think we should fix the caching API in the main build and only distribute a single one. But perhaps there are other options, like e.g. requiring a different name that also dismisses the caching features. Opinions?

### Anything else?

I'm sure there might be other things missing from this list, which are impacted by the planned changes. So please add anything that comes to mind!

**Comment by lesion** [comment] 2016-09-29 16:18
## Module docs and schemas
imo the natural place for schema and documentation is the code.
I think it is also possible to extract JSON-LD schema directly from source code ...
I'm currently using [explainjs](https://github.com/bendytree/explainjs) and [slate](https://lord.github.io/slate/#introduction) for documentation but don't know if match the needs.

## Module console
Wow! this is a great idea ! Didn't notice it.
And yep, this could be a separated npm module.
Would also be nice to have a module skeleton!

## No-cache build
I perfectly agree on this. There's no need to make a different build with cache disabled, this
should be an option of RS to me (like `new RemoteStorage({logging: true, cache: false})`)
I can take a look on this if you want.

**Comment by skddc** [comment] 2016-10-09 18:14
> I think it is also possible to extract JSON-LD schema directly from source code

Yes, but the question I see is -- due to the fact that we need the schema in at least one more place as seperate file anyway (the document behind the JSON-LD context URL ideally) -- doesn't it make more sense to define it in a seperate file and have the module include it from there as well. Also because that would enable different modules to include the same schemas (which might arguably be wrong as well).

> Would also be nice to have a module skeleton!

Totally agree. But I also think we should have a more refined module structure and all the problems I outlined solved before creating something like a module generator/skeleton for people to use.

> I can take a look on this if you want.

Sure, that'd be great.

**Comment by silverbucket** [comment] 2016-10-20 10:01
@lesion - I'm trying to take a look at the issues you pointed out with `jairbu` and `webfinger.js` but I have some questions: 

For `jaribu`, you're saying you want to prefix the path search my `./src` instead of `./`? I'm not sure I understand the problem here, or what you changed that broke the tests? Maybe if I know more about your needs I can figure out what needs fixing? 

For `webfinger.js`, I could include something like `isomorphic-fetch` however that adds a considerable amount of size to the library. Right now, the `xmlhttprequest` module creates a shim for the node-specific environment, in which size is less important. Again, I'm not sure what the actual problem is - if the code already runs in the browser and in node, what are we trying to fix?

**Comment by skddc** [comment] 2016-10-20 10:24
@silverbucket The latest code for this should be available in the `feature/949-noglobal` branch, in case you want to run the tests yourself there.

**Comment by silverbucket** [comment] 2016-10-20 10:29
@skddc I did try them out, everything fails, but when I look at the setup they do seem to load the files. That's why I was confused by the path comments. For example I ran `access-suite.js` and get this:

**Comment by lesion** [comment] 2016-10-20 14:07
I'm using `feature/949-noglobal` branch for this: what changed is that `RemoteStorage` is no more global but needs to be required when needed (eg. https://github.com/remotestorage/remotestorage.js/blob/feature/949-noglobal/src/access.js#L1)

This change create an issue to the test suite because `./src/` path is used to require remotestorage source (https://github.com/remotestorage/remotestorage.js/blob/feature/949-noglobal/test/unit/access-suite.js#L13) but then './' is now used inside tested "module".
I was trying to remove `./src` prefix from unit test, hoping there was a way to specify the app directory jaribu is testing, but there's not (https://github.com/silverbucket/jaribu/blob/master/bin/jaribu#L16-L20).

I think a flag `--app-dir` would be enough to solve this issue.

```bash
➜ remotestorage.js git:(feature/949-noglobal) ✗  ./node_modules/jaribu/bin/jaribu  test/unit/access-suite.js
jaribu is in: /media/dev/remotestorage.js/node_modules/jaribu/bin/../
app is in: /media/dev/remotestorage.js/node_modules/jaribu/bin/../../../
```
or there's another way to change the app dir ?

**Comment by silverbucket** [comment] 2016-10-20 14:22
@lesion I'm still a little confused. That output says the app is in the project root. You want it to say it's in '[path]/../../../src' ? Can't you just add the src prefix to the paths in the define statement? But, again, it looks like the files are being included right now - on that branch. Sorry if I'm being dense, I just don't yet understand what the actual crux of the issue is.

Can you give me an example of how you'd expect it to work?

**Comment by lesion** [comment] 2016-10-20 14:47
I could add ./src in test suite as you suggest (actually there is, so I don't really have to add it).
The point now is that inside the source of `src/access.js` I'm now using `require('./remotestorage.js')`
so I have 2 requires (the one in unit test and the one of the library itself introduced by this branch).
Obviously the library path is relative, and cannot be changed, because it will break the whole library (that require is used by webpack in this branch)!! Jaribu instead will search it inside the root path of the project and not relatively from where its required.

```
➜  remotestorage.js git:(feature/949-noglobal) ✗ node_modules/jaribu/bin/jaribu test/unit/access-suite.js 
jaribu is in: /media/dev/remotestorage.js/node_modules/jaribu/bin/../
app is in: /media/dev/remotestorage.js/node_modules/jaribu/bin/../../../


...
 FAIL access setup failed 
Error: Evaluating /media/dev/remotestorage.js/node_modules/jaribu/bin/../../../src/access.js as module
 "src/access" failed with error: Error: Tried loading "remotestorage" at 
/media/dev/remotestorage.js/node_modules/jaribu/bin/../../../remotestorage.js then tried node's 
require("remotestorage") and it failed with error: Error: Cannot find module 'remotestorage'


```

**Comment by lesion** [comment] 2016-10-20 14:55
> Can you give me an example of how you'd expect it to work?

I would suggest a flag `--app-dir` to set `appDir` (so `requirejs` baseUrl configuration will follow).

**Comment by silverbucket** [comment] 2016-10-20 15:13
Aha I see, so the problem isn't that jaribu can't find the files to require, it's that `require` is searching for files at the root of the project directory, which breaks things when - in the rs code - require is used. 

Thanks @lesion, this helps to clarify the problem.

**Comment by lesion** [comment] 2016-10-20 15:18
yep exactly, sorry for the confusion.

**Comment by silverbucket** [comment] 2016-10-20 20:10
After looking at this for a while, I realized that the remotestorage.js tests are for some reason including `requirejs` and then using that to load modules, which is why the `requirejs` path settings are being used. Simply removing that requirement from the beginning of the tests, and rewriting `requirejs` statements to use `require` instead, the tests are able to load the files with much more simplicity. However a new problem occurs which is that the global.RemoteStorage property is no longer set, and when - for example - `access.js` is loaded using `require` nothing is sent back (no `module.exports`)...

**Comment by silverbucket** [comment] 2016-10-20 20:16
I meant removing `requirejs` and including `require`. I've pushed the change to the `access-suite.js` to illustrate my point.
https://github.com/remotestorage/remotestorage.js/commit/d5d94ce28f83cb9803c13898376b810944bccc0f

**Comment by lesion** [comment] 2016-10-20 20:41
You're a genius and I've solved with this and another little push (including RemoteStorage with require):
087b501

```bash
➜ remotestorage.js git:(feature/949-noglobal) ✗ ./node_modules/jaribu/bin/jaribu  test/unit/access-suite.js
jaribu is in: /media/dev/remotestorage.js/node_modules/jaribu/bin/../
app is in: /media/dev/remotestorage.js/node_modules/jaribu/bin/../../../
[ '/media/dev/remotestorage.js/test/unit/access-suite.js' ]

running... 1 suites, 30 tests.
[...cut...]
scaffolding report  0 failed,  122 passed, 0 skipped, 62 total.
       test report  0 failed,  30 passed, 0 skipped, 30 total.


  OK  all tests passed!
```

**Comment by lesion** [comment] 2016-10-20 20:43
PS. Don't know if this will work upstream because I've not pushed some work in progress I've to clean before pushing.

**Comment by lesion** [comment] 2016-10-20 20:52
PPS. In mid-long-term, would be better to have each rs module to export itself so, instead of requiring `remotestorage.js` in each module, would be better to do the reverse thing. 
For example having a module `log.js` and requiring it when needed (from `remotestorage.js` for example).

This will permit to require only the tested module in unit tests and of course a really cleaner and better library (but this is quite a bit of refactoring).

**Comment by silverbucket** [comment] 2016-10-20 20:53
Great! Glad it's working, and yes I was thinking the same thing about the requiring dynamic.

**Comment by skddc** [comment] 2016-10-21 12:26
> instead of requiring remotestorage.js in each module, would be better to do the reverse thing.

Certainly. I would also prefer to use ES6 modules/imports then. But I think we can start with this in order to get down to a single production build, and then move on from there, right?

**Comment by skddc** [comment] 2016-10-24 13:22
@lesion So, what do you think is missing for your branch to become a pull request? You can just prefix the title with [WIP] if it's still work in progress, but the tests will then be run for every push, and we can collaborate on the code.

**Comment by lesion** [comment] 2016-10-26 00:41
pull request on #951 

Don't know why lot of tests are complaining about:
`TypeError: this._pendingGPD is not a function`

I've merged @skddc `feature/remove_widget` branch, hope you are ok with this.
To experiment all remoteStorage features, I'm currently using this branch 
inside a [chrome-extension](https://github.com/lesion/memm/) with bookmarks module,
I've also prepared a [remoteStorageWidget vue component] (https://github.com/lesion/memm/blob/master/app/remoteStorage.vue) (that's why I needed to
merge `feature/remove_widget` branch) so probably I would add some effort in remotestorage-widget repo and use that instead.

**Comment by skddc** [comment] 2016-10-26 11:10
Great!

> I've merged @skddc feature/remove_widget branch, hope you are ok with this.

Yes, it's fine. I'll open a pull request for that one soon. But have to finish the new widget first, of course.

**Comment by skddc** [comment] 2016-10-26 11:55
> I've also prepared a remoteStorageWidget vue component (that's why I needed to
> merge feature/remove_widget branch) so probably I would add some effort in remotestorage-widget repo and use that instead.

Sure, feel free to dig in! I just added new issues and a milestone for the things that are missing for the final switch:

https://github.com/remotestorage/remotestorage-widget/milestone/1

There's probably more. Feel free to create new issues, of course.

**Comment by skddc** [comment] 2017-04-28 09:37
This has actually landed in master. I'd like to kindly request everyone PARTY HARD!

![party-hard](https://cloud.githubusercontent.com/assets/842/25523424/ef342884-2c06-11e7-8015-94b8bca0f53d.gif)

**Closed** 2017-04-28 09:37 UTC
Labels: in progress
